#!/bin/bash

# Quick checklist for Vercel Firebase setup

echo "🔍 Vercel Firebase Deployment Checklist"
echo "======================================"
echo ""
echo "Step 1: Set Vercel Environment Variables"
echo "  [ ] Go to https://vercel.com/dashboard"
echo "  [ ] Click on 'stack-app' project"
echo "  [ ] Go to Settings > Environment Variables"
echo "  [ ] Add all 6 EXPO_PUBLIC_* variables"
echo ""
echo "Step 2: Authorize Vercel Domain in Firebase"
echo "  [ ] Go to https://console.firebase.google.com"
echo "  [ ] Select 'stack-bd031' project"
echo "  [ ] Go to Authentication > Settings > Authorized domains"
echo "  [ ] Click 'Add domain'"
echo "  [ ] Add: stack-app-ochre.vercel.app"
echo "  [ ] Save"
echo ""
echo "Step 3: Redeploy"
echo "  [ ] Go back to Vercel dashboard"
echo "  [ ] Click on 'stack-app' project"
echo "  [ ] Go to Deployments tab"
echo "  [ ] Click the '...' menu on latest deployment"
echo "  [ ] Click 'Redeploy'"
echo "  [ ] Wait for deployment to complete"
echo ""
echo "Step 4: Test"
echo "  [ ] Open https://stack-app-ochre.vercel.app/"
echo "  [ ] Press F12 to open Developer Tools"
echo "  [ ] Go to Console tab"
echo "  [ ] You should see: ✅ Firebase initialized successfully"
echo ""
echo "If you still see errors:"
echo "  - Check browser console for exact error message"
echo "  - Verify all 6 env vars are set in Vercel"
echo "  - Verify domain is added in Firebase authorized domains"
echo "  - Try clearing browser cache (Ctrl+Shift+Delete)"
